# Generated by Django 2.2.6 on 2019-11-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_remove_notificacion_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='asunto',
            field=models.CharField(default='asunto', max_length=50),
            preserve_default=False,
        ),
    ]
