# Generated by Django 2.2.6 on 2019-11-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0005_notificacion_asunto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name_plural': 'Notificaciones'},
        ),
    ]
