# Generated by Django 2.2.6 on 2019-11-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='user_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Profile'),
        ),
    ]
