# Generated by Django 2.2.6 on 2019-11-20 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0008_auto_20191120_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Profile'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='user_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
