# Generated by Django 2.2.6 on 2019-11-20 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0004_auto_20191120_1610'),
        ('bases', '0009_auto_20191120_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='user_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usr.Profile'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='uc',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
