# Generated by Django 2.2.6 on 2019-11-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0010_auto_20191120_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='user_sender',
        ),
    ]
