# Generated by Django 2.2.6 on 2019-12-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0005_auto_20191206_1416'),
        ('bases', '0013_auto_20191206_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Agencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='agencia',
            name='usuarios',
            field=models.ManyToManyField(through='bases.User_Agencia', to='usr.Profile'),
        ),
    ]
