# Generated by Django 2.2.6 on 2019-12-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0014_auto_20191206_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ('codigo',), 'verbose_name_plural': 'Provincias'},
        ),
    ]
