# Generated by Django 2.2.6 on 2019-12-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0004_auto_20191120_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
